### ISSUE TITLE
Errors in subscriptions are swallowed by emit

### ISSUE THREAD

**Issue by davestimpert** [losandes/polyn-async-events#7]
If I `emit` an event, and the subscriber to that even throws an error, it doesn't go anywhere.

Example:

```javascript
const { Topic } = require('@polyn/async-events')
const topic = new Topic({ topic: 'myTopic' })

topic.subscribe('message', (body) => {
  console.log(`received ${body}`)
  throw new Error('subscriber error')
})

const emitResult = topic.emit('message', 'body')

emitResult.then(result => {
  console.log('emit result:', result)
})

topic.subscribe('error', console.error) // this does nothing
```

I would expect one of two solutions (that I can think of so far)

1. This could raise an `unhandledRejection`
2. There could be an option to subscribe to unhandled subscription errors

Either of these options would at least allow for an opportunity to log the error.

**Comment by losandes** [comment]
Better late than never... PR #11 addresses this issue if you have time to take a look, @davestimpert.

**Comment by davestimpert** [comment]
Before:
```
❯ node try.js
received body
emit result: {
  count: 1,
  meta: {
    id: 'myTopic::message::v9wmlyfh',
    time: 1652702764709,
    topic: 'myTopic',
    event: 'message'
  }
}
```

### After

```
❯ node try.js
received body
emit result: {
  count: 1,
  meta: {
    id: 'myTopic::message::e83vu659',
    time: 1652702790384,
    topic: 'myTopic',
    event: 'message'
  }
}
Error: subscriber error
    at Object.receiver (/Users/dstimpert/repos/polyn-async-events/try.js:6:9)
    at /Users/dstimpert/repos/polyn-async-events/src/publish.js:88:43
    at Array.map (<anonymous>)
    at /Users/dstimpert/repos/polyn-async-events/src/publish.js:86:48 {
  id: 'myTopic::error::m79u7652',
  time: 1652702790391,
  topic: 'myTopic',
  event: 'error',
  reportVerbosity: 'none',
  subscriptionId: 'myTopic::error::48q5p22c'
}
```

🙌 Thanks &y!

**Comment by losandes** [comment]
Thanks for verifying, Dave!
